version: '3'

networks:
  traefik-net:
    external: true
  stack-net:
    internal: true

services:
  nextcloud-nginx:
    image: nginx:alpine
    container_name: nextcloud-nginx
    restart: always
    expose:
      - 80
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=80
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud.clfp.fr,cloud.clfp.fr,nuage.clfp.fr
#      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/03_nextcloud/nextcloud:/var/www/html:ro
      - /mnt/DATA/DOCKER/03_nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud-database
      - nextcloud-fpm
    networks:
      - traefik-net
      - stack-net

  nextcloud-fpm:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-fpm
    restart: always
    expose:
      - 9000
    environment:
      - TZ=Europe/Paris
    user: 1500:1500
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/DATA/DOCKER/03_nextcloud/nextcloud:/var/www/html
      - /mnt/DATA/USERS:/raid_storage/USERS
      - /mnt/DATA/MEDIA:/raid_storage/MEDIA
    depends_on:
      - nextcloud-database
    networks:
      - stack-net

  nextcloud-database:
    image: postgres:alpine
    container_name: nextcloud-database
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    env_file: postgresql_secret.env
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/DATA/DOCKER/03_nextcloud/postgresql:/var/lib/postgresql
    networks:
      - stack-net
