version: '3'

networks:
  traefik-net:
    external: true
  stack-net:
    internal: true

services:
  nginx:
    image: nginx:alpine
    container_name: lemp-nginx
    restart: always
    expose:
      - 80
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=80
      - traefik.backend=lemp
      - traefik.frontend.rule=Host:kraken.clfp.fr
#      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - app:/usr/share/nginx/app:ro
    depends_on:
      - database
      - php
    networks:
      - traefik-net
      - stack-net

  php:
    image: php:rc-fpm-alpine
    container_name: lemp-php
    restart: always
    expose:
      - 9000
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.enable=false
    networks:
      - stack-net

  database:
    image: mysql:latest
    container_name: lemp-database
    restart: always
    expose:
     - 3306
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=azerty123
    labels:
      - traefik.enable=false
    networks:
      - stack-net
