version: '2'

networks:
  traefik-net:
    external: true
  lan:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: 10.33.0.0/24
        - gateway: 10.33.0.1
        - ip_range: 10.33.0.4/32

              - lan:
          ipv4_address: 10.33.0.5