version: '3'

networks:
  traefik-net:
    external: true
  stack-net:
    internal: true

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    expose:
      - 80
    env_file: db.env
    environment:
      - WORDPRESS_DB_HOST=wordpress_db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=80
      - traefik.backend=wordpress
      - traefik.frontend.rule=Host:wplist.clfp.fr
      - traefik.frontend.auth.basic=enzo:$$apr1$$UwwVAZHs$$ndp7E0d.hka.CMWN.BPsr1
    volumes:
      - /mnt/DATA/DOCKER/99_wordpress/wordpress:/var/www/html
    depends_on:
      - wordpress_db
    networks:
      - traefik-net
      - stack-net

  wordpress_db:
    image: mysql
    container_name: wordpress_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    env_file: db.env
    volumes:
      - /mnt/DATA/DOCKER/99_wordpress/db:/var/lib/mysql
    networks:
      - stack-net
