version: '3'

networks:
  traefik-net:
    external: true

services:

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command: --api --docker
    ports:
      - 80:80     # Http
      - 443:443   # Https
    expose:
      - 8080
    env_file:
      - /mnt/DATA/DOCKER/01_traefik/ovh-api-secret.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.clfp.fr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Listen to docker events (unix sock)
      - /mnt/DATA/DOCKER/01_traefik/traefik.toml:/traefik.toml
      - /mnt/DATA/DOCKER/01_traefik/acme:/acme
    networks:
      - traefik-net
