version: '2'

networks:
  traefik-net:
    external: true
  stack-net:
    internal: true
  lan-net:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: 192.168.1.254/24
          gateway: 192.168.1.254
#          ip-range: 192.168.1.254/30

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    expose:
      - 80
      - 67/tcp
      - 67/udp
    environment:
      - TZ=Europe/Paris
      - VIRTUAL_HOST=pihole.clfp.fr
#/!\ on local, access using host_ip:8082/admin/. add /admin/
      - DNS1=9.9.9.9
      - DNS2=1.1.1.1
      - DNSMASQ_LISTENING=all
    env_file:
      - pihole-password.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=80
      - traefik.backend=pihole
      - traefik.frontend.rule=Host:pihole.clfp.fr
#      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/02_pihole/pihole/:/etc/pihole/
      - /mnt/DATA/DOCKER/02_pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 9.9.9.9
    networks:
      traefik-net: null
      stack-net: null

  dhcp-helper:
    build: ./dhcp-helper
    container_name: dhcp-helper
    restart: always
    command: -s pihole
    cap_add:
      - NET_ADMIN
    depends_on:
      - pihole
    networks:
      stack-net: null
      lan-net:
        ipv4_address: 192.168.1.5
