version: '3'

networks:
  traefik-net:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    expose:
      - 80
    environment:
      - TZ=Europe/Paris
      - VIRTUAL_HOST=pihole.clfp.fr
#/!\ on local, access using host_ip:8082/admin/. add /admin/
      - DNS1=9.9.9.9
      - DNS2=1.1.1.1
    env_file:
      - pihole-password.env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.protocol=http
      - traefik.port=80
      - traefik.backend=pihole
      - traefik.frontend.rule=Host:pihole.clfp.fr
#      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/02_pihole/pihole/:/etc/pihole/
      - /mnt/DATA/DOCKER/02_pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 9.9.9.9
    networks:
      traefik-net: null
